---

- name: Montar clientes nfs fstab
  blockinfile:
       path: /etc/fstab
       state: present
       block: |
          10.0.2.10:/mnt/shared_directory/ /mnt/shared_directory/ nfs defaults 0 0
  become_user: root
  become: true

- name: Crear fichero de configuración para el runtime cri-o
  file:
    path: "/etc/modules-load.d/crio.conf"
    state: "touch"
  become: true

- name: Configurar pre-requisitos para cri-o
  blockinfile:
     path: "/etc/modules-load.d/crio.conf"
     block: |
           overlay
           br_netfilter
  become: true

- name: Cargar módulos requeridos
  shell: |
       modprobe overlay
       modprobe br_netfilter
  become: true

- name: Apertura de puerto para el masquerade 
  firewalld:
    masquerade: yes
    permanent: true
    state: enabled
  become: true

- name: Recargar firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Configuración de red para Kubernetes
  file:
    path: "/etc/sysctl.d/k8s.conf"
    state: "touch"
  become: true


- name: Añadir configuración para k8s
  blockinfile:
    path: "/etc/sysctl.d/k8s.conf"
    block: |
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
        net.bridge.bridge-nf-call-ip6tables = 1
  become: true

- name: Aplicar cambios en /etc/sysctl.d/k8s.conf
  command: sysctl --system
  become: true 

- name: Añadir repositorio libcontainers
  command: curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
  become: true

- name: Añadir Repositorio cri-o
  command: curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.24.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.24/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.24.repo
  become: true

- name: Instalando cri-o
  dnf:
    name: "cri-o"
    state: present
  become: true

- name: Habilitar e iniciar cri-o
  systemd: 
    name: crio
    state: started
    enabled: yes
    masked: no
  become: true

- name: Crear repositorio para Kubernetes
  file:
    path: "/etc/yum.repos.d/kubernetes.repo"
    state: "touch"
  become: true

- name: Escribir información del repositorio para Kubernetes
  blockinfile:
     path: "/etc/yum.repos.d/kubernetes.repo"
     block: |
       [kubernetes]
       name=Kubernetes
       baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
       enabled=1
       gpgcheck=1
       repo_gpgcheck=1
       gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  become: true

- name: Kubelet
  dnf:
    name: "kubelet"
    state: present
    disable_excludes: "kubernetes"
  become: true

- name: Kubeadm
  dnf:
    name: "kubeadm"
    state: present
    disable_excludes: "kubernetes"
  become: true

- name: kubectl
  dnf:
    name: "kubectl"
    state: present
    disable_excludes: "kubernetes"
  become: true

- name: Iniciar kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
  become: true