apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
#    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: jenkins.sgdcaso2.com
    http:
      paths:
      - path: /
        backend: 
          serviceName: jenkins
          servicePort: 8080
  tls:
    - hosts:
      - jenkins.sgdcaso2.com
      secretName: jenkins-tls
