---

- name: Apertura puerto 8285/udp
  firewalld:
    port: 8285/udp
    permanent: true
    state: enabled

- name: Apertura puerto 8472/udp
  firewalld:
    port: 8472/udp
    permanent: true
    state: enabled

- name: abrir puerto 6443/tcp
  firewalld:
    port: 6443/tcp
    permanent: true
    state: enabled

- name: abrir puerto 10250/tcp (Kubelet API)
  firewalld:
    port: 10250/tcp
    permanent: true
    state: enabled

- name: abrir puerto 30000-32767/tcp 
  firewalld:
    port: 30000-32767/tcp
    permanent: true
    state: enabled
    
- name: Recargar firewalld
  systemd:
    name: firewalld
    state: reloaded

# Comentar este comando en una segunda ejecución del playbook sobre el mismo entorno
- name: unir worker al cluster (kubeadm join)
  command: kubeadm join {{ ip_master }}:6443 --token {{ token }} --discovery-token-ca-cert-hash sha256:{{ hash }}
  become: true

- name: Reiniciar worker
  command: init 6